### ISSUE TITLE
Error when I run The project in the workspace

### ISSUE THREAD

**Issue by ramsserio** [victorBaro/ironhack-week3#1]
Hello ,
When I run the app in the workspace I get the following errors : 
"Fabric: This app relies on Fabric. Please sign up for access at https://fabric.io/sign_up,install Fabric.app then ask a team member to invite you to this app's organization.If this machine is a build server please remove Fabric.app if present and use xcodebuild so that Week3.app.dSYM is uploaded.Command /bin/sh failed with exit code 1"
What should I do to run it correctly ?
Thank you,

**Comment by victorBaro** [comment]
I will update the project soon with a fix.
In the meantime, you can disable fabric script from xcode project settings or install Fabric (http://fabric.io) in your computer.

**Comment by ramsserio** [comment]
I've installed fabric and it is working !
Thank's
